chart = {
"1":"Shegzzy Frosh.911",
"2":"MEC DECIMAL.Colour Rage",
"3":"MEC DECIMAL.Eyes Closed",
"4":"Rexx.Hellflames",
"5":"Enny West.Say Your Name",
"6":"Lieky.More Love",
"7":"Enny West.My Girl",
"8":"Lieky.Love Damages",
"9":"Promzywild.Fuck Boy",
"10":"Lieky.Sungba",
"11":"Enny West.Go Crazy",
"12":"Enny West.Rollercoaster",
"13":"Lieky.Shawty",
"14":"Enny West.Wordings On The Closet",
"15":"Lieky.Come Take",
"16":"Lieky.Daddy",
"17":"Lieky.Money Love",
"18":"Lieky.Elevate",
"19":"Enny West and Cee Jay.Shooting Star",
"20":"Fordman DLA.You",
"21":"DahVey.nla_",
"22":"Vic Smart.Superstar Legacy",
"23":"Ad3sola.Where You Dey",
"24":"Ad3sola.Love IS Not For Me",
"25":"Ad3sola.Live Life",
"26":"Big Gold.Calm Down",
"27":"Lithoxx.Emotional Pains",
"28":"Klymax9.Dead Inside",
"29":"Emmz.Better Days",
"30":"Marvin Grayson.Party",
"31":"Timmy Tammy.Ice On My Neck",
"32":"Chukam.Destiny",
"33":"AG Blaze.cant_stop",
"34":"Black Danker.Interceptor",
"35":"Lithoxx.Heartless",
"36":"Sh3ddy Dickson and Aajaay.Wipe My Tears",
"37":"Lithoxx.On My Mind",
"38":"Neon Mik3y.Trap",
"39":"Cruizy B.Joy Is Coming",
"40":"Jectro.Blue",
"41":"Lithoxx.Wildside",
"42":"Timmy Tammy.Hating on Me",
"43":"Oni Banks.Hearty",
"44":"Emmy Lob.Squad Style",
"45":"Da Riddim.louder",
"46":"Deszy Dsn.Body",
"47":"Emojie.Loading",
"48":"Kamikaze.Open",
"49":"Lithoxx.My Universe",
"50":"Marvin Grayson.Tonight",
"51":"Marvin Grayson.Fire",
"52":"Marvin Grayson.Controller",
"53":"Marvin Grayson.G'rayson",
"54":"Marvin Grayson.Monster",
"55":"Marvin Grayson.Little Beginning RMK",
"56":"Marvin Grayson.Special",
"57":"Marvin Grayson.STARZ",
"58":"MEC DECIMAL.Hellow Darkness",
"59":"MEC DECIMAL.Hipidi Hop",
"60":"MEC DECIMAL.The Raven",
"61":"MEC DECIMAL.Happy Birthday Ruby",
"62":"Schway.South London",
"63":"Timmy Tammy.Dripping Boss",
"64":"Wale Tunes.Na God O",
"65":"Wilfred.Controller",
"66":"Yummy Cruise.On God",
"67":"Yunik Lord.Bad Girl"
}
