chart = {
"1":"Rexx.Hellflames",
"2":"Enny West.Say Your Name",
"3":"Lieky.More Love",
"4":"Enny West.My Girl",
"5":"Lieky.Love Damages",
"6":"Promzywild.Fuck Boy",
"7":"Lieky.Sungba",
"8":"Enny West.Go Crazy",
"9":"Enny West.Rollercoaster",
"10":"Lieky.Shawty",
"11":"Enny West.Wordings On The Closet",
"12":"Lieky.Come Take",
"13":"Lieky.Daddy",
"14":"Lieky.Money Love",
"15":"Lieky.Elevate",
"16":"Enny West and Cee Jay.Shooting Star",
"17":"Fordman DLA.You",
"18":"DahVey.nla_",
"19":"Vic Smart.Superstar Legacy",
"20":"Ad3sola.Where You Dey",
"21":"Ad3sola.Love IS Not For Me",
"22":"Ad3sola.Live Life",
"23":"Big Gold.Calm Down",
"24":"Lithoxx.Emotional Pains",
"25":"Klymax9.Dead Inside",
"26":"Emmz.Better Days",
"27":"Marvin Grayson.Party",
"28":"Timmy Tammy.Ice On My Neck",
"29":"Chukam.Destiny",
"30":"AG Blaze.cant_stop",
"31":"Black Danker.Interceptor",
"32":"Lithoxx.Heartless",
"33":"Sh3ddy Dickson and Aajaay.Wipe My Tears",
"34":"Lithoxx.On My Mind",
"35":"Neon Mik3y.Trap",
"36":"Cruizy B.Joy Is Coming",
"37":"Jectro.Blue",
"38":"Lithoxx.Wildside",
"39":"Timmy Tammy.Hating on Me",
"40":"Oni Banks.Hearty",
"41":"Emmy Lob.Squad Style",
"42":"Da Riddim.louder",
"43":"Deszy Dsn.Body",
"44":"Emojie.Loading",
"45":"Kamikaze.Open",
"46":"Lithoxx.My Universe",
"47":"Marvin Grayson.Tonight",
"48":"Marvin Grayson.Fire",
"49":"Marvin Grayson.Controller",
"50":"Marvin Grayson.G'rayson",
"51":"Marvin Grayson.Monster",
"52":"Marvin Grayson.Little Beginning RMK",
"53":"Marvin Grayson.Special",
"54":"Marvin Grayson.STARZ",
"55":"MEC DECIMAL.Colour Rage",
"56":"MEC DECIMAL.Eyes Closed",
"57":"MEC DECIMAL.Hellow Darkness",
"58":"MEC DECIMAL.Hipidi Hop",
"59":"MEC DECIMAL.The Raven",
"60":"MEC DECIMAL.Happy Birthday Ruby",
"61":"Schway.South London",
"62":"Shegzzy Frosh.911",
"63":"Timmy Tammy.Dripping Boss",
"64":"Wale Tunes.Na God O",
"65":"Wilfred.Controller",
"66":"Yummy Cruise.On God",
"67":"Yunik Lord.Bad Girl"
}